### ISSUE TITLE
Database-Connection

### ISSUE THREAD

**Issue by JanLoebel** [fuinorg/keycloak-postgres-testready#1]
Hi there :)

Just wanted to let you know that the current image doesn't setup a Postgres connection. If you have a look at the startup logs or the Server-Info in the Keycloak-Admin-Area you will see that it uses the in memory h2-database.

Best regards,
Jan

**Comment by michael-schnell** [comment]
Ouch... I  only used the image for testing so far and it was always dropped after the test. I'm going to check what is wrong with it.

**Comment by michael-schnell** [comment]
After some inestifation it seems that the base image "jboss/keycloak-postgres:3.3.0.CR1" does not work correctly.  It has a XSL stylesheet that should replace the H2 datasource with the PostgreSQL one. This does not work, because the XSL sheet has the namespace "urn:jboss:domain:datasources:4.0" but the actual namespace is "urn:jboss:domain:datasources:5.0". 

I thought about fixing this, but in the meantime the database code was moved to the main keycloak image and they replaced the XSL with Jboss CLI to change the datasource. Therfore I will deprecate this image and create a new one based on the new Keycloak image.

**Comment by michael-schnell** [comment]
The new image is now available here: https://github.com/fuinorg/keycloak-testready
It now works with both mysql and postgres.
